apiVersion: batch/v1
kind: Job
metadata:
  name: blockface-preproc-job-%JOBID%
spec:
  backoffLimit: 2
  template:
    metadata:
      name: blockface-preproc-pod
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gse-key
      containers:
      - name: blockface-preproc-container
        image: pyushkevich/histoannot-preproc-simple:latest
        command: ["/bin/bash"]
        args: ["prep_bucket.sh", "process_dir", 
               "-k", "/var/secrets/google/key.json",
               "-j", "98", "-n", 
               "gs://mtl_histology/%ID%/bf_raw",
               "gs://mtl_histology/%ID%/bf_proc"]
        resources:
          limits:
            memory: "8Gi"
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      restartPolicy: Never
      activeDeadlineSeconds: 36000
