apiVersion: batch/v1
kind: Job
metadata:
  name: bf-mchan-job-%JOBID%
spec:
  backoffLimit: 2
  template:
    metadata:
      name: my-gpu-pod-torch
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gse-key
      containers:
      - name: my-gpu-container-torch
        image: pyushkevich/tangle-cnn-prod:latest
        command: ["/bin/bash"]
        args: ["process_blockface_block.sh", "cfn-cluster-test", "%ID%", "%BLOCK%", "%SEC0%", "%SEC1%"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      restartPolicy: Never
      activeDeadlineSeconds: 10800
