apiVersion: batch/v1
kind: Job
metadata:
  name: hist-torch-job-%JOBID%
spec:
  backoffLimit: 2
  template:
    metadata:
      name: my-gpu-pod-torch
    spec:
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gse-key
      containers:
      - name: my-gpu-container-torch
        image: pyushkevich/tangle-cnn-prod
        command: ["/bin/bash"]
        args: ["wildcat_analyze_wsi.sh",
               "-s", "%INPUT%",
               "-n", "%NETWORK%",
               "-o", "%OUTPUT%",
               "-p", "cfn-cluster-test",
               "-k", "/var/secrets/google/key.json",
               "-W", "1536",
               "-D", "%DOWNSAMPLE%"]
        resources:
          limits:
            nvidia.com/gpu: 1
            memory: "8Gi"
        volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
      restartPolicy: Never
      activeDeadlineSeconds: 7200
